<a href="https://colab.research.google.com/github/FilledVaccum/Courses/blob/default-main/CampusX/100_days_of_ML/Day_30_Function_Transformer_%7C_Log_Transform_%7C_Reciprocal_Transform_%7C_Square_Root_Transform_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import scipy.stats as stats

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

In [18]:
df = pd.read_csv('train.csv', usecols=['Age', 'Fare', 'Survived'])

In [19]:
df.head(20)

    Survived   Age     Fare
0          0  22.0   7.2500
1          1  38.0  71.2833
2          1  26.0   7.9250
3          1  35.0  53.1000
4          0  35.0   8.0500
5          0   NaN   8.4583
6          0  54.0  51.8625
7          0   2.0  21.0750
8          1  27.0  11.1333
9          1  14.0  30.0708
10         1   4.0  16.7000
11         1  58.0  26.5500
12         0  20.0   8.0500
13         0  39.0  31.2750
14         0  14.0   7.8542
15         1  55.0  16.0000
16         0   2.0  29.1250
17         1   NaN  13.0000
18         0  31.0  18.0000
19         1   NaN   7.2250

In [20]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [15]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

<ipython-input-15-7ee7fe972bc2>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

In [17]:
df.head(20)

    Survived        Age     Fare
0          0  22.000000   7.2500
1          1  38.000000  71.2833
2          1  26.000000   7.9250
3          1  35.000000  53.1000
4          0  35.000000   8.0500
5          0  29.699118   8.4583
6          0  54.000000  51.8625
7          0   2.000000  21.0750
8          1  27.000000  11.1333
9          1  14.000000  30.0708
10         1   4.000000  16.7000
11         1  58.000000  26.5500
12         0  20.000000   8.0500
13         0  39.000000  31.2750
14         0  14.000000   7.8542
15         1  55.000000  16.0000
16         0   2.000000  29.1250
17         1  29.699118  13.0000
18         0  31.000000  18.0000
19         1  29.699118   7.2250

In [23]:
X = df.iloc[:, 1:3]
y = df.iloc[:, 0]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)