<a href="https://colab.research.google.com/github/FilledVaccum/Courses/blob/default-main/Udemy/Complete%20Guide%20to%20Building%2C%20Deploying%2C%20and%20Optimizing%20Generative%20AI%20with%20Langchain%20and%20Huggingface/Machine%20Learning%20for%20NLP/45_One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.DataFrame(
    {
        'color' : ['red', 'blue', 'green', 'yellow', 'red', 'green']
    }
)

In [3]:
print("Orginal Data:")
print(data)

Orginal Data:
    color
0     red
1    blue
2   green
3  yellow
4     red
5   green

In [4]:
encoded_data = pd.get_dummies(data['color'], prefix='color')

In [5]:
print("After OHE:")
print(encoded_data)

After OHE:
   color_blue  color_green  color_red  color_yellow
0       False        False       True         False
1        True        False      False         False
2       False         True      False         False
3       False        False      False          True
4       False        False       True         False
5       False         True      False         False

### What are disadvantages of One Hot Encoding ?
1.  Curse of Dimensionality:

    Creates high-dimensional sparse matrices

    Each unique category adds a new column to the dataset

    As categories increase, the number of dimensions grows exponentially

2. Memory and Computational Issues:

    Requires more memory to store the transformed data

    Increases computational complexity

    Can slow down model training, especially with limited resources

    Creates sparse matrices where most values are zeros

3. Loss of Information:

    Doesn't capture relationships between categories

    No semantic meaning between related categories

    For example, words like "run", "walk", and "shoe" would have no relationship in the encoded space despite being semantically related

4. Potential Overfitting:

    The increased number of features can lead to overfitting

    Models might learn patterns in the sparse data that don't generalize well

5. Scalability Issues:

    Not practical for categorical variables with many unique values

    For example, if you have a category with 1000 unique values, you'll end up with 1000 new columns

6. Storage Inefficiency:

    Requires more storage space

    Most values in the matrix will be zeros, leading to inefficient storage utilization

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [16]:
data['color']

0       red
1      blue
2     green
3    yellow
4       red
5     green
Name: color, dtype: object

In [13]:
encoded_data = encoder.fit_transform(data[['color']])

In [14]:
encoded_data

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [10]:
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(['color']))

In [15]:
encoded_df

   color_blue  color_green  color_red  color_yellow
0         0.0          0.0        1.0           0.0
1         1.0          0.0        0.0           0.0
2         0.0          1.0        0.0           0.0
3         0.0          0.0        0.0           1.0
4         0.0          0.0        1.0           0.0
5         0.0          1.0        0.0           0.0

In [11]:
final_df = pd.concat([data, encoded_df], axis=1)

In [12]:
final_df

    color  color_blue  color_green  color_red  color_yellow
0     red         0.0          0.0        1.0           0.0
1    blue         1.0          0.0        0.0           0.0
2   green         0.0          1.0        0.0           0.0
3  yellow         0.0          0.0        0.0           1.0
4     red         0.0          0.0        1.0           0.0
5   green         0.0          1.0        0.0           0.0